- name: Get NexusRepo CRD
  kubernetes.core.k8s_info:
    api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    host: "{{ nexus_k8s_host | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: nexusrepos.sonatype.com
  register: nexusrepo_crd
  retries: 10
  delay: 1

- name: Delete nexus instance
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    host: "{{ nexus_k8s_host | default(omit) }}"
    api_version: sonatype.com/v1alpha1
    kind: NexusRepo
    name: nexusrepo
    namespace: nexus
    wait: true
    wait_sleep: 15
    wait_timeout: 120
  when: nexusrepo_crd.resources | length != 0

- name: Remove Project nexus
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    host: "{{ nexus_k8s_host | default(omit) }}"
    api_version: project.openshift.io/v1
    kind: Project
    name: nexus
    namespace: nexus
    wait: true
    wait_sleep: 15
    wait_timeout: 120
