- name: Get AssetRepository CRD
  kubernetes.core.k8s_info:
    api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    host: "{{ asset_repo_k8s_host | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: assetrepositories.integration.ibm.com
  register: assetrepository_crd
  retries: 10
  delay: 1

- name: Delete AssetRepository instance
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    host: "{{ asset_repo_k8s_host | default(omit) }}"
    api_version: integration.ibm.com/v1beta1
    kind: AssetRepository
    name: assets
    namespace: "{{ asset_repo_project_name }}"
    wait: true
    wait_sleep: 15
    wait_timeout: 120
  when: assetrepository_crd.resources | length != 0

- name: Wait for Client to disappear
  kubernetes.core.k8s_info:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    api_version: oidc.security.ibm.com/v1
    kind: Client
    name: assets-ibm-integration-asset-repository-oidc-client
    namespace: "{{ cp4ba_project_name }}"
  register: client
  retries: 30
  delay: 10
  until: client.resources | length == 0
  ignore_errors: true

- name: Clear Client finalizers
  ansible.builtin.include_role:
    name: common
    tasks_from: clear-resource-finalizers
  vars:
    common_k8s_api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ asset_repo_k8s_host | default(omit) }}"
    common_api_version: oidc.security.ibm.com/v1
    common_kind: Client
    common_resource_name: assets-ibm-integration-asset-repository-oidc-client
    common_namespace_name: "{{ asset_repo_project_name }}"
  when: client.resources | length != 0

- name: Remove Assets Operator
  ansible.builtin.include_role:
    name: common
    tasks_from: remove-operator
  vars:
    common_k8s_api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ asset_repo_k8s_host | default(omit) }}"
    common_namespace_name: "{{ asset_repo_project_name }}"
    common_label_selector_stub: "ibm-integration-asset-repository"

- name: Wait for CouchDBCluster instances removal
  kubernetes.core.k8s_info:
    api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    host: "{{ asset_repo_k8s_host | default(omit) }}"
    api_version: couchdb.databases.cloud.ibm.com/v1
    kind: CouchDBCluster
    namespace: "{{ asset_repo_project_name }}"
  register: copach_db_clusters
  retries: 60
  delay: 30
  until: copach_db_clusters.resources | length == 0

- name: Remove CoachDB Operator
  ansible.builtin.include_role:
    name: common
    tasks_from: remove-operator
  vars:
    common_k8s_api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ asset_repo_k8s_host | default(omit) }}"
    common_namespace_name: "{{ asset_repo_project_name }}"
    common_label_selector_stub: "couchdb-operator"
