cp4ba_action: install
cp4ba_base_dir: /tmp
cp4ba_dir_name: cp4ba
cp4ba_k8s_api_key: ""
cp4ba_k8s_host: ""
## Should not be changed in particular guide version.
## Version of the Subscription channel as defined on
## https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=cluster-setting-up-in-openshift-console
cp4ba_operator_channel: v21.3
cp4ba_starting_csv: ibm-cp4a-operator.v21.3.9
## Should not be changed in particular guide version.
## Version of Cloud Pak CASE archive as found on
## https://github.com/IBM/cloud-pak/tree/master/repo/case/ibm-cp-automation e.g. 3.0.1
cp4ba_case_version: 3.2.9
## Should not be changed in particular guide version.
## Version of cert-kubernetes folder from Cloud Pak CASE archive e.g. 21.0.1
cp4ba_case_cert_k8s_version: 21.0.3
cp4ba_storage_class_name: ""
## Should not be changed in particular guide version.
## Version of Cloud Pak e.g. 20.0.2.1, 20.0.3
cp4ba_version: 21.0.3
## Name of the CP4BA instance in cr.yaml at path metadata.name
cp4ba_cr_meta_name: cp4ba
## Name of OCP CP4BA project
cp4ba_project_name: cp4ba
cp4ba_automation_base_version: v2
cp4ba_automation_ui_config_version: v1
cp4ba_universal_password: ""
cp4ba_icr_password: ""
cp4ba_ldap_hostname: ""
cp4ba_db2_hostname: ""
cp4ba_mongodb_hostname: ""
cp4ba_mail_hostname: ""
cp4ba_kibana_url: ""
cp4ba_wildcard_key_path: ""
cp4ba_wildcard_crt_path: ""
cp4ba_ca_key_path: ""
cp4ba_ca_crt_path: ""
cp4ba_external_share_google: ""
cp4ba_google_client_id: ""
cp4ba_google_client_secret: ""
cp4ba_deployment_platform: ""
cp4ba_output_namespace: "apollo-one-shot"
