mongo_express_action: install
mongo_express_base_dir: /tmp
mongo_express_dir_name: mongo-express
mongo_express_k8s_api_key: ""
mongo_express_k8s_host: ""
mongo_express_image_tag: 0.54.0
mongo_express_ca_crt_path: ""
mongo_express_wildcard_key_path: ""
mongo_express_wildcard_crt_path: ""
mongo_express_universal_password: ""
mongo_express_mongodb_hostname: ""
