- name: Create Mongo Express directory for generated files
  ansible.builtin.file:
    path: "{{ mongo_express_output_directory }}"
    state: directory
    mode: u+rwx

- name: Create Project
  ansible.builtin.include_role:
    name: common
    tasks_from: create-project
  vars:
    common_k8s_api_key: "{{ mongo_express_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ mongo_express_k8s_host | default(omit) }}"
    common_namespace_name: mongo-express
    common_output_directory: "{{ mongo_express_output_directory }}"

- name: Prepare yaml file for Deployment
  ansible.builtin.template:
    src: deployment.yaml.j2
    dest: "{{ mongo_express_output_directory }}/deployment.yaml"
    mode: u+rwx

- name: Add Deployment
  kubernetes.core.k8s:
    api_key: "{{ mongo_express_k8s_api_key | default(omit) }}"
    host: "{{ mongo_express_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ mongo_express_output_directory }}/deployment.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 600

- name: Prepare yaml file for Service
  ansible.builtin.template:
    src: service.yaml.j2
    dest: "{{ mongo_express_output_directory }}/service.yaml"
    mode: u+rwx

- name: Add Service
  kubernetes.core.k8s:
    api_key: "{{ mongo_express_k8s_api_key | default(omit) }}"
    host: "{{ mongo_express_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ mongo_express_output_directory }}/service.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Get OCP Apps Endpoint
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_k8s_api_key: "{{ mongo_express_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ mongo_express_k8s_host | default(omit) }}"
    common_output_to_var: "apps_endpoint_domain"
  when: apps_endpoint_domain is not defined

- name: Crete Edge Route
  ansible.builtin.include_role:
    name: common
    tasks_from: create-edge-route
  vars:
    common_k8s_api_key: "{{ mongo_express_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ mongo_express_k8s_host | default(omit) }}"
    common_namespace_name: mongo-express
    common_route_name: mongo-express
    common_service_name: mongo-express
    common_wildcard_crt_path: "{{ mongo_express_wildcard_crt_path }}"
    common_wildcard_key_path: "{{ mongo_express_wildcard_key_path }}"
    common_ca_crt_path: "{{ mongo_express_ca_crt_path }}"
    common_apps_endpoint_domain: "{{ apps_endpoint_domain }}"
    common_output_directory: "{{ mongo_express_output_directory }}"
