- name: Get ProcessMining CRD
  kubernetes.core.k8s_info:
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: processminings.processmining.ibm.com
  register: processmining_crd
  retries: 10
  delay: 1

- name: Delete ProcessMining instance
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    api_version: processmining.ibm.com/v1beta1
    kind: ProcessMining
    name: processmining
    namespace: "{{ pm_project_name }}"
    wait: true
    wait_sleep: 15
    wait_timeout: 120
  when: processmining_crd.resources | length != 0

- name: Delete Secrets
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    api_version: v1
    kind: Secret
    name: "{{ item }}"
    namespace: "{{ pm_project_name }}"
    wait: true
    wait_sleep: 15
    wait_timeout: 120
  with_items:
    - pm-dbs
    - pm-tls-secret

- name: Remove Operators
  ansible.builtin.include_role:
    name: common
    tasks_from: remove-operator
  vars:
    common_k8s_api_key: "{{ pm_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ pm_k8s_host | default(omit) }}"
    common_namespace_name: "{{ pm_project_name }}"
    common_label_selector_stub: "{{ item }}"
  with_items:
    - "ibm-automation-processmining"
    - "db2u-operator"

- name: Get DB2 Pod
  kubernetes.core.k8s_info:
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    api_version: v1
    kind: Pod
    namespace: db2
    label_selectors:
      - component=db2oltp
  register: pods
  retries: 40
  delay: 15

- name: Delete Db2 for IPM
  block:

    - name: Connect to DB
      kubernetes.core.k8s_exec:
        api_key: "{{ pm_k8s_api_key | default(omit) }}"
        host: "{{ pm_k8s_host | default(omit) }}"
        namespace: db2
        pod: "{{ pods.resources[0].metadata.name }}"
        command: >
          su - db2inst1 -s /usr/bin/bash -c "
          db2 connect to CP4BA;
          "
      register: db_connect_status
      ignore_errors: true

    - name: Delete pm db2
      block:

        - name: Delete Tablespaces
          kubernetes.core.k8s_exec:
            api_key: "{{ pm_k8s_api_key | default(omit) }}"
            host: "{{ pm_k8s_host | default(omit) }}"
            namespace: db2
            pod: "{{ pods.resources[0].metadata.name }}"
            command: >
              su - db2inst1 -s /usr/bin/bash -c "
              db2 connect to CP4BA;
              db2 DROP TABLESPACE {{ item }};
              "
          register: command_status
          failed_when: command_status.rc != 0 and command_status.stdout is not search('.*\"'+item+'\" is an undefined name.*')
          with_items:
            - PM_TS
            - PM_TEMP_TS
            - PM_SYSTMP_TS

        - name: Delete Schema
          kubernetes.core.k8s_exec:
            api_key: "{{ pm_k8s_api_key | default(omit) }}"
            host: "{{ pm_k8s_host | default(omit) }}"
            namespace: db2
            pod: "{{ pods.resources[0].metadata.name }}"
            command: >
              su - db2inst1 -s /usr/bin/bash -c "
              db2 connect to CP4BA;
              db2 \"CALL SYSPROC.ADMIN_DROP_SCHEMA('PM', NULL, 'ERRORSCHEMA', 'ERRORTABLE')\";
              "
          retries: 10
          delay: 2
          register: command_status
          failed_when: command_status.rc != 0 and command_status.stdout is not search('.*-601:CREATE TABLE.*')

        - name: Remove DB2 user
          ansible.builtin.include_role:
            name: common
            tasks_from: remove-db2-user
          vars:
            common_k8s_api_key: "{{ pm_k8s_api_key | default(omit) }}"
            common_k8s_host: "{{ pm_k8s_host | default(omit) }}"
            common_db2_user: pm

      when: (db_connect_status.rc == 0)

  when: (pods.resources | length != 0)

- name: Get Mongo DB pod
  kubernetes.core.k8s_info:
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    api_version: v1
    kind: Pod
    namespace: mongodb
    label_selectors:
      - app.kubernetes.io/component=mongodb
  register: mongodb_pod

- name: Delete PM Mongo DB
  kubernetes.core.k8s_exec:
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    namespace: mongodb
    pod: "{{ mongodb_pod.resources[0].metadata.name }}"
    command: >
      mongo --username root --password {{ pm_universal_password }} --authenticationDatabase admin
      --eval '{{ item }}' mongodb://localhost:27017/processmining
  register: command_status
  with_items:
    - db.dropUser("root")
    - db.dropDatabase()
  when: mongodb_pod.resources | length != 0
