- name: Remove Catalog Sources
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ catalog_source_k8s_api_key | default(omit) }}"
    host: "{{ catalog_source_k8s_host | default(omit) }}"
    api_version: v1alpha1
    kind: CatalogSource
    name: "{{ item }}"
    namespace: openshift-marketplace
    wait: true
  with_items:
    - ibm-operator-catalog
    - ibm-cp4a-operator-catalog
    - ibm-cp-automation-foundation-catalog
    - ibm-automation-foundation-core-catalog
    - opencloud-operators
    - ibm-db2uoperator-catalog
    - bts-operator
    - cloud-native-postgresql-catalog
