- name: Remove Project db2mc
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ db2mc_k8s_api_key | default(omit) }}"
    host: "{{ db2mc_k8s_host | default(omit) }}"
    api_version: project.openshift.io/v1
    kind: Project
    name: db2mc
    wait: true
    wait_sleep: 15
    wait_timeout: 120

- name: Remove DB
  ansible.builtin.include_role:
    name: common
    tasks_from: remove-db
  vars:
    common_k8s_api_key: "{{ db2mc_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ db2mc_k8s_host | default(omit) }}"
    common_db2_db_name: DB2MC
