- name: Remove Project mail
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ mail_k8s_api_key | default(omit) }}"
    host: "{{ mail_k8s_host | default(omit) }}"
    api_version: project.openshift.io/v1
    kind: Project
    name: mail
    wait: true
    wait_sleep: 15
    wait_timeout: 120

- name: Remove CRB mail-privileged
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ cerebro_k8s_api_key | default(omit) }}"
    host: "{{ cerebro_k8s_host | default(omit) }}"
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: mail-privileged
    wait: true
    wait_sleep: 15
    wait_timeout: 120
