- name: Create directory for generated files
  ansible.builtin.file:
    path: "{{ mongodb_output_directory }}"
    state: directory
    mode: u+rwx

- name: Create Project
  ansible.builtin.include_role:
    name: common
    tasks_from: create-project
  vars:
    common_k8s_api_key: "{{ mongodb_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ mongodb_k8s_host | default(omit) }}"
    common_namespace_name: mongodb
    common_output_directory: "{{ mongodb_output_directory }}"

- name: Prepare yaml file for anyuid ClusterRoleBinding
  ansible.builtin.template:
    src: anyuid-scc-clusterrolebinding.yaml.j2
    dest: "{{ mongodb_output_directory }}/anyuid-scc-clusterrolebinding.yaml"
    mode: u+rwx

- name: Add anyuid ClusterRoleBinding
  kubernetes.core.k8s:
    api_key: "{{ mongodb_k8s_api_key | default(omit) }}"
    host: "{{ mongodb_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ mongodb_output_directory }}/anyuid-scc-clusterrolebinding.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Add bitnami chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Prepare yaml file for values of helm chart
  ansible.builtin.template:
    src: values.yaml.j2
    dest: "{{ mongodb_output_directory }}/values.yaml"
    mode: u+rwx

- name: Deploy mongodb chart using values files on target
  kubernetes.core.helm:
    api_key: "{{ mongodb_k8s_api_key | default(omit) }}"
    host: "{{ mongodb_k8s_host | default(omit) }}"
    name: mongodb
    chart_ref: bitnami/mongodb
    chart_version: "{{ mongodb_chart_version }}"
    release_namespace: mongodb
    values_files:
      - "{{ mongodb_output_directory }}/values.yaml"

- name: Wait for mongodb Deployment to be Available
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-resource-condition
  vars:
    common_k8s_api_key: "{{ mongodb_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ mongodb_k8s_host | default(omit) }}"
    common_api_version: v1
    common_resource_kind: Deployment
    common_resource_name: mongodb
    common_resource_namespace: mongodb
    common_condition_name: Available
    common_retries: 80
    common_delay: 15
