---
- name: CP4BA Enterprise
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - variables.yml
    - internal-variables.yml
  tasks:
    - name: Input Validations
      ansible.builtin.include_role:
        name: validations
        tasks_from: input-validations

    - name: Install CP4BA Enterprise
      include_tasks: install.yml
      when: "global_action == 'install'"

    - name: Remove CP4BA Enterprise
      include_tasks: remove.yml
      when: "global_action == 'remove'"
