- name: Remove PM
  ansible.builtin.include_role:
    name: pm
  when: pm_enabled
  
- name: RPA group
  block:

    - name: Remove RPA
      ansible.builtin.include_role:
        name: rpa

    - name: Remove MSSQL
      ansible.builtin.include_role:
        name: mssql

  when: rpa_enabled

- name: Remove Asset Repo
  ansible.builtin.include_role:
    name: asset_repo
  when: asset_repo_enabled

- name: Remove CP4BA
  ansible.builtin.include_role:
    name: cp4ba

- name: Remove CPFS
  ansible.builtin.include_role:
    name: cpfs

- name: Remove Mongo Express
  ansible.builtin.include_role:
    name: mongo_express
  when: mongo_express_enabled

- name: Remove MongoDB
  ansible.builtin.include_role:
    name: mongodb

- name: Remove Kibana
  ansible.builtin.include_role:
    name: kibana

- name: Remove AKHQ
  ansible.builtin.include_role:
    name: akhq
  when: akhq_enabled

- name: Remove Cerebro
  ansible.builtin.include_role:
    name: cerebro
  when: cerebro_enabled

- name: Remove Roundcube
  ansible.builtin.include_role:
    name: roundcube
  when: roundcube_enabled

- name: Remove Mail
  ansible.builtin.include_role:
    name: mail

- name: Remove nexus
  ansible.builtin.include_role:
    name: nexus

- name: Remove gitea
  ansible.builtin.include_role:
    name: gitea

- name: Remove openldap
  ansible.builtin.include_role:
    name: openldap

- name: Remove DB2MC
  ansible.builtin.include_role:
    name: db2mc
  when: db2mc_enabled

- name: Remove DB2
  ansible.builtin.include_role:
    name: db2

- name: Remove Global CA
  ansible.builtin.include_role:
    name: global_ca

- name: Remove Catalog Source
  ansible.builtin.include_role:
    name: catalog_source
