- name: Validate filled in Entries
  ansible.builtin.fail:
    msg: "The {{ item.name }} variable has to be defined and have a value"
  when: "not item.value or item.value == None or item.value | length == 0"
  with_items:
    - name: storage_class_name
      value: "{{ storage_class_name }}"
