- name: ICR Password should be defined
  ansible.builtin.fail:
    msg: "The icr_password variable has to be defined."
  when: icr_password is not defined

- name: ICR Password should not be empty
  ansible.builtin.fail:
    msg: "The icr_password is not correct, it shouldn't be empty."
  when: not icr_password or icr_password | length == 0

- name: ICR Password should not be TODO_ICR_PASSWORD
  ansible.builtin.fail:
    msg: "The icr_password is not correct, it shouldn't be TODO_ICR_PASSWORD."
  when: icr_password is regex(".*TODO_ICR_PASSWORD.*")

- name: ICR Password registry login validation call
  ansible.builtin.uri:
    url: "https://cp.icr.io/oauth/token"
    method: GET
    user: cp
    password: "{{ icr_password }}"
    status_code:
      - 200
      - 401
  register: icr_login_response

- name: ICR Password  registry login validation
  ansible.builtin.fail:
    msg: "The icr_password is not correct, we've got unauthorized from the cp.icr.io registry, please verify the icr_password."
  when: icr_login_response.status != 200
