- name: ICR Password
  include_tasks: icr-password.yml

- name: Universal Password
  include_tasks: universal-password.yml

- name: Boolean Variables
  include_tasks: boolean-variables.yml

- name: Empty Variables
  include_tasks: empty-variables.yml

- name: Choice List Variables
  include_tasks: choice-list-variables.yml

- name: OCP Access
  include_tasks: ocp-access.yml
