- name: Get OCP Version
  ansible.builtin.uri:
    url: "{{ ocp_api_endpoint | default(omit) }}/version"
    method: GET
    timeout: 10
  register: validate_ocp_api_endpoint
  failed_when: false
  when: ocp_api_endpoint is defined

- name: OCP API Endpoint url should be reachable
  ansible.builtin.fail:
    msg: "Incorrect url provided as the OCP API Endpoint"
  when: ocp_api_endpoint is defined and validate_ocp_api_endpoint.status and not (200 <= validate_ocp_api_endpoint.status < 300)

- name: Validate if the given OCP credentials work, get namespaces
  kubernetes.core.k8s_info:
    api_key: "{{ ocp_cluster_token | default(omit) }}"
    host: "{{ ocp_api_endpoint | default(omit) }}"
    kind: Namespace
    wait: true
    wait_sleep: 2
    wait_timeout: 5
  register: validate_ocp_namespaces
  failed_when: false

- name: OCP API Endpoint url should be reachable
  ansible.builtin.fail:
    msg: "Incorrect url provided as the OCP API Endpoint"
  when:
    validate_ocp_namespaces is not defined or
    ("msg" in validate_ocp_namespaces and "Error" in validate_ocp_namespaces.msg ) or
    ("exception" in validate_ocp_namespaces and "NewConnectionError" in validate_ocp_namespaces.exception)

- name: OCP Cluster Token has to be valid
  ansible.builtin.fail:
    msg: "Incorrect token provided as the OCP Cluster Token"
  when:
    validate_ocp_namespaces is not defined or
    ("exception" in validate_ocp_namespaces) and ("Unauthorized" in validate_ocp_namespaces.exception)
