# Example of the functionality call
#
# - name: Create ICR Secret
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: create-icr-secret
#   vars:
#     common_k8s_api_key: "{{ prefix_k8s_api_key | default(omit) }}"
#     common_k8s_host: "{{ prefix_k8s_host | default(omit) }}"
#     common_output_directory: "{{ prefix_output_directory }}"
#     common_icr_secret_name: _secret_name
#     common_icr_password: "{{ prefix_icr_password }}"
#     common_namespace_name: _namespace_name

- name: Set IBM Container Registry JSON
  ansible.builtin.set_fact:
    container_registry_json: '{{ {"auths": {"cp.icr.io": {"username": "cp", "password": common_icr_password} }} | to_json | b64encode }}'

- name: Prepare yaml file for IBM Container Registry Secret
  ansible.builtin.template:
    src: icr-secret.yaml.j2
    dest: "{{ common_output_directory }}/icr-secret.yaml"
    mode: u+rwx

- name: Add IBM Container Registry Secret
  kubernetes.core.k8s:
    api_key: "{{ common_k8s_api_key | default(omit) }}"
    host: "{{ common_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ common_output_directory }}/icr-secret.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15
