# Example of the functionality call
#
# - name: Remove DB
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: remove-db
#   vars:
#     common_k8s_api_key: "{{ prefix_k8s_api_key | default(omit) }}"
#     common_k8s_host: "{{ prefix_k8s_host | default(omit) }}"
#     common_db2_db_name: _db2_db_name

- name: Get DB2 Pod
  kubernetes.core.k8s_info:
    api_key: "{{ common_k8s_api_key | default(omit) }}"
    host: "{{ common_k8s_host | default(omit) }}"
    api_version: v1
    kind: Pod
    namespace: db2
    label_selectors:
      - component=db2oltp
  register: pods
  retries: 40
  delay: 15

- name: Delete DB
  kubernetes.core.k8s_exec:
    api_key: "{{ common_k8s_api_key | default(omit) }}"
    host: "{{ common_k8s_host | default(omit) }}"
    namespace: db2
    pod: c-db2ucluster-db2u-0
    command: >
      su - db2inst1 -s /usr/bin/bash -c "
      db2 connect to {{ common_db2_db_name }};
      db2 force application all;
      sleep 30;
      db2 connect reset;
      db2 deactivate db {{ common_db2_db_name }};
      db2 drop db {{ common_db2_db_name }};
      "
  register: command_status
  failed_when: command_status.rc != 0
    and command_status.stdout is not search('.*SQL1013N  The database alias name or database name \"'+common_db2_db_name+'\".*')
  when: pods.resources | length != 0
