# Example of the functionality call
#
# - name: Wait for CRD
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: wait-crd
#   vars:
#     common_k8s_api_key: "{{ prefix_k8s_api_key | default(omit)  }}"
#     common_k8s_host: "{{ prefix_k8s_host | default(omit) }}"
#     common_crd_name: crd_name

- name: Wait for '{{ common_crd_name }}' CRD to be Established
  kubernetes.core.k8s_info:
    api_key: "{{ common_k8s_api_key | default(omit) }}"
    host: "{{ common_k8s_host | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "{{ common_crd_name }}"
  register: common_crd
  retries: 10
  delay: 1
  until: ('True' in common_crd | json_query(condition_query) | unique )
  vars:
    condition_query: "resources[0].status.conditions[?type == 'Established'].status"
